//tealium universal tag - utag.247 ut4.0.202412041458, Copyright 2024 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
u.ev={"view":1,"link":1};u.initialized=false;u.map={};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
var conversion_id=b['Google_Ads_Conversion_ID'];var label_id=b['Google_Ads_label_ID'];var transaction_id=b['_corder'];var value=b['order_amount_ati_without_sf'];var revenu=b['order_amount_tf_without_sf'];var value_ati_with_sf=b['order_amount_ati_with_sf'];var discount=b['order_discount_ati'];var country=b['env_country'];var order_id=b['_corder'];var price_unitprice_tf=b['_cprice'];var quantity=b['_cquan'];var currency=b['_ccurrency'];window.dataLayer=window.dataLayer||[];var gtag=function(){dataLayer.push(arguments);};if(b['env_country']==='IT'){window.dataLayer=window.dataLayer||[];gtag=function(){dataLayer.push(arguments);};gtag('js',new Date());gtag('config','AW-941817811');}
if(b['env_country']==='IT'&&b['pageType']==='ConfirmationOrderPage'){order_id=Array.isArray(b["multi_products_id"])?b["multi_products_id"]:b["multi_products_id"].split(";");var items=[];for(i=0;i<order_id.length;i++){var current_product_id=order_id[i];var current_price_unitprice_tf=price_unitprice_tf[i];var current_quantity=quantity[i];var obj={"discount":'',"id":current_product_id,"price":current_price_unitprice_tf,"quantity":current_quantity,};items.push(obj);}
gtag('event','purchase',{'send_to':'AW-941817811/5H-mCIv3kIgBENP_i8ED','value':parseFloat(b['order_amount_ati_without_sf']),'transaction_id':b._ccustid,'discount':b.order_discount_ati,'aw_merchand_id':"100553562",'aw_feed_country':country,'aw_feed_language':b['env_language'].toUpperCase(),'items':items,'currency':currency});gtag('config','AW-941817811',{'allow_enhanced_conversions':true});}
if(b['env_country']==='CH'){window.dataLayer=window.dataLayer||[];gtag=function(){dataLayer.push(arguments);};gtag('js',new Date());gtag('config','AW-1011037781');}
if(b['env_country']==='CH'&&b['pageType']==='ConfirmationOrderPage'){gtag('set','user_data',{"sha256_email_adress":b.user_email_sha256,"adress":{"first_name":b.user_firstname,"last_name":b.user_lastname,"postal_code":b.user_postalcode,"country":b.env_country}});gtag('event','conversion',{'send_to':'AW-1011037781/f1IyCOT9rqwZENXsjOID','value':value_ati_with_sf,'currency':currency,'transaction_id':order_id});}
if(b['env_country']==='BE'){window.dataLayer=window.dataLayer||[];gtag=function(){dataLayer.push(arguments);};gtag('js',new Date());gtag('config','AW-936738266',{'allow_enhanced_conversions':true,'user_id':b.user_id,});}
if(b['env_country']==='BE'&&b['pageType']==='ConfirmationOrderPage'){gtag('set','user_data',{"sha256_email_adress":b.user_email_sha256,"adress":{"first_name":b.user_firstname,"last_name":b.user_lastname,"postal_code":b.user_postalcode,"country":b.env_country}});gtag('event','conversion',{'send_to':'AW-936738266/4Yz9CIjdy2IQ2vvVvgM','value':revenu,'currency':currency,'transaction_id':order_id});}
if(b['env_country']==='ES'){window.dataLayer=window.dataLayer||[];gtag=function(){dataLayer.push(arguments);};gtag('js',new Date());gtag('config','AW-1069848356',{'allow_enhanced_conversions':true,});}
if(b['env_country']==='ES'&&b['pageType']==='ConfirmationOrderPage'){gtag('set','user_data',{"sha256_email_adress":b.user_email_sha256});gtag('event','conversion',{'send_to':'AW-1069848356/h3AICI-3j4gBEKSukv4D','value':parseFloat(value),'currency':currency,'transaction_id':order_id});}
if(b['env_country']==='ES'&&window.location.href.includes('business')){var gtag_report_conversion=function(url){var callback=function(){if(typeof(url)!='undefined'){window.location=url;}};gtag('event','conversion',{'send_to':'AW-1069848356/fK3SCP2c1Y4YEKSukv4D','event_callback':callback});return false;};}
if(b['env_country']==='PT'){window.dataLayer=window.dataLayer||[];gtag=function(){dataLayer.push(arguments);};gtag('js',new Date());gtag('config','AW-955294809',{'allow_enhanced_conversions':true,});}
if(b['env_country']==='PT'&&b['pageType']==='ConfirmationOrderPage'){gtag('set','user_data',{"sha256_email_adress":b.user_email_sha256});gtag('event','conversion',{'send_to':'AW-955294809/RyPnCOiQtHkQ2cjCxwM','value':revenu,'currency':'EUR','transaction_id':order_id});}
if(b['env_country']==='UK'){window.dataLayer=window.dataLayer||[];gtag=function(){dataLayer.push(arguments);};gtag('js',new Date());gtag('config','AW-995148005',{'allow_enhanced_conversions':true,});}
if(b['env_country']==='UK'&&b['pageType']==='ConfirmationOrderPage'){gtag('set','user_data',{'sha256_email_address':b.user_email_sha256});gtag('event','conversion',{'send_to':'AW-995148005/4IkwCJDPjFYQ5YHD2gM','value':parseFloat(value),'currency':currency,'transaction_id':order_id});}
if(b['env_country']==='UK'){var google_conversion_id=995148005;var google_custom_params=window.google_tag_params;var google_remarketing_only=true;var scriptElt1=document.createElement("script");scriptElt1.type="text/javascript";scriptElt1.src="https://www.googleadservices.com/pagead/conversion_async.js";scriptElt1.charset="utf-8";(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]||document.getElementsByTagName('script')[0].parentNode).insertBefore(scriptElt1,null);var adwordsTracker={pad:function(str,max){str=str.toString();return str.length<max?pad("0"+str,max):str;},offerId:function(){var article=_page.GetArticle();return adwordsTracker.ProductId+adwordsTracker.pad(article.Dimension1,4)+adwordsTracker.pad(article.Dimension2,4)+adwordsTracker.DocumentId;},skuId:function(){var article=_page.GetArticle();return article.ProductId;},getSkuAndPageType:function(){var page_template=b["env_template"];if((page_template=="PDP")&&(_page.article)){return{ecomm_prodid:this.offerId()}
ecomm_prodid=adwordsTracker.offerId();}
else
return{ecomm_prodid:null}},productTrack:function(pagetype){var custom_ecomm_prodid=null;var trackerResult=adwordsTracker.getSkuAndPageType();custom_ecomm_prodid=trackerResult.ecomm_prodid;var custom_ecomm_page=null;if(pagetype)
custom_ecomm_page=pagetype;else
custom_ecomm_page="product";if(window.google_trackConversion){window.google_trackConversion({google_conversion_id:995148005,google_custom_params:window.google_tag_params,google_remarketing_only:true,ecomm_pagetype:custom_ecomm_page,ecomm_prodid:custom_ecomm_prodid});}},allPageTracker:function(){if(window.google_trackConversion){window.google_trackConversion({google_conversion_id:995148005,google_custom_params:window.google_tag_params,google_remarketing_only:true});}}};(function(){try{$(".pdp-filter-item").on("click",adwordsTracker.productTrack);}
catch(e){}}());adwordsTracker.allPageTracker();}
if(window.location.href.includes('com')){window.dataLayer=window.dataLayer||[];gtag=function(){dataLayer.push(arguments);};gtag('js',new Date());gtag('config','AW-941817811',{'allow_enhanced_conversions':true,});}
if(window.location.href.includes('com')&&b.useful_visit==='true'){gtag('event','Useful Visit',{'send_to':'AW-941817811/fOOkCK-C8NgZENP_i8ED',});}
if(window.location.href.includes('/shoppingbasket/confirmorderglobale')&&window.location.href.includes('laredoute.com')||window.location.href.includes('.com')&&b.pageType==='ConfirmationOrderPage'){gtag('set','user_data',{'sha256_email_address':b.user_email_sha256});gtag('event','purchase',{'send_to':'AW-941817811/5H-mCIv3kIgBENP_i8ED','value':b['order_amount_ati_without_sf'],'transaction_id':b['order_id'],'discount':b['order_ship_ati'],'aw_merchand_id':"101433751",'aw_feed_country':b['env_country'],'aw_feed_language':b['env_language'].toUpperCase(),'currency':b['order_currency']});}
if(b['env_country']==='DE'){window.dataLayer=window.dataLayer||[];gtag=function(){dataLayer.push(arguments);};gtag('js',new Date());gtag('config','AW-941817811',{'allow_enhanced_conversions':true,});}
if(b['env_country']==='DE'&&b.useful_visit==='true'){gtag('event','Useful Visit',{'send_to':'AW-941817811/fOOkCK-C8NgZENP_i8ED',});}
if(b['env_country']==='DE'&&b['pageType']==='ConfirmationOrderPage'){gtag('set','user_data',{'sha256_email_address':b.user_email_sha256});gtag('event','conversion',{'send_to':'AW-941817811/5H-mCIv3kIgBENP_i8ED','value':(isNaN(parseFloat(value))?"":parseFloat(value)),'currency':currency,'transaction_id':order_id});}
if(b['env_country']==='NL'){window.dataLayer=window.dataLayer||[];gtag=function(){dataLayer.push(arguments);};gtag('js',new Date());gtag('config','AW-936738266',{'allow_enhanced_conversions':true,});}
if(b['env_country']==='NL'&&b['pageType']==='ConfirmationOrderPage'){gtag('set','user_data',{'sha256_email_address':b.user_email_sha256});gtag('event','conversion',{'send_to':'AW-936738266/4Yz9CIjdy2IQ2vvVvgM','value':(isNaN(parseFloat(revenu))?"":parseFloat(revenu)),'currency':currency,'transaction_id':order_id});}
if(b['env_country']==='FR'){window.dataLayer=window.dataLayer||[];gtag=function(){dataLayer.push(arguments);};gtag('js',new Date());gtag('config','AW-10991718627',{'allow_enhanced_conversions':true,});gtag('config','AW-1017398570',{'allow_enhanced_conversions':true,});gtag('config','DC-5863518');gtag('config','DC-10585054');gtag('event','conversion',{'allow_custom_scripts':true,'u1':b['pageType'],'send_to':'DC-10585054/visit/lared0+unique'});gtag('event','conversion',{'send_to':'AW-10991718627/QSQaCM-EruUYEOOhofko'});}
if(b['env_country']==='FR'&&(b['env_template']==='HP'||b['env_template']==='PLP'||b['env_template']==='PDP')){var text="ecomm_prodid="+";ecomm_pagetype="+b['pageType']+";ecomm_totalvalue="+";a="+''+";g="+b['user_gender']+";hasaccount="+b['google_rem']+";cqs="+''+";rp="+''+";ly="+''+";hs="+''+";audiencesCRM="+'FLOW1-LIFE-'+b["seg_engagement"];var img=document.createElement("img");img.type="text/javascript";img.src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/"+'1028414086'+"/?label="+''+"&script=0&url="+b['dom.domain']+"&data="+encodeURIComponent(text);(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]||document.getElementsByTagName('script')[0].parentNode).insertBefore(img,null);}
if(b['env_country']==='FR'&&(b['env_template']==='Basket, Step 1'||b['pageType']==='ConfirmationOrderPage')){text="ecomm_prodid="+b['_cprod'].join(', ')+";ecomm_pagetype="+b['pageType']+";ecomm_category="+b['_ccat']+";ecomm_pvalue="+b['_cprice'].join(', ')+";ecomm_quantity="+b['_cquan'].join(', ')+";ecomm_totalvalue="+b['order_amount_tf_without_sf']+";a="+''+";g="+b['user_gender']+";hasaccount="+b['google_rem']+";cqs="+''+";rp="+''+";ly="+''+";hs="+'';img=document.createElement("img");img.type="text/javascript";img.src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/"+'1028414086'+"/?label="+''+"&script=0&url="+b['dom.domain']+"&data="+encodeURIComponent(text);(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]||document.getElementsByTagName('script')[0].parentNode).insertBefore(img,null);}
if(b['env_country']==='FR'&&b['pageType']==='ConfirmationOrderPage'){gtag('set','user_data',{'sha256_email_address':b.user_email_sha256});gtag('event','conversion',{'send_to':'AW-1017398570/5YsICI7V-QYQqoqR5QM','value':revenu,'currency':currency,'transaction_id':order_id});gtag('event','conversion',{'send_to':'AW-10991718627/_q_FCP3v5JsYEOOhofko','value':revenu,'currency':currency,'transaction_id':order_id});gtag('event','conversion',{'send_to':'AW-10991718627/QSQaCM-EruUYEOOhofko'});gtag('config','AW-1017398570',{'allow_enhanced_conversions':'true'});order_id=Array.isArray(b["multi_products_id"])?b["multi_products_id"]:b["multi_products_id"].split(";");var tab_product=[];for(i=0;i<order_id.length;i++){var current_product_id=order_id[i];var current_price_unitprice_tf=price_unitprice_tf[i];var current_quantity=quantity[i];var obj={"id":current_product_id,"price":current_price_unitprice_tf,"quantity":current_quantity,};tab_product.push(obj);}
gtag('event','purchase',{'allow_custom_scripts':true,'value':revenu,'transaction_id':order_id,'items':tab_product,'u1':b['env_channel'],'u2':b['env_language'],'u3':country,'u4':b['user_gender'],'u5':b['user_is_new_customer'],'u6':b['basket_type'],'u7':b['google_rem'],'u8':'60','PRD':{'ecommerce':{'purchase':{'products':tab_product}}},'send_to':'DC-5863518/trans123/trans0+transactions'});var result_strings={};for(i=0;i<b.multi_products_trademark.length;i++){var product_string=`${b.multi_products_trademark[i]}|${b.multi_products_sold_by_redoute[i]}|${b.multi_products_id[i]}|${b.multi_products_unitprice_tf[i]}`;result_strings[`u${i+2}`]=product_string;}
gtag('event','purchase',{'allow_custom_scripts':true,'value':revenu,'transaction_id':order_id,...result_strings,'send_to':'DC-10585054/sale/lared0+transactions'});}
if(b['env_country']==='RU'){var google_conversion_id=1008742867;var google_custom_params=window.google_tag_params;var google_remarketing_only=true;var scriptElt1=document.createElement("script");scriptElt1.type="text/javascript";scriptElt1.src="//www.googleadservices.com/pagead/conversion.js";scriptElt1.async=true;scriptElt1.defer='defer';(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]||document.getElementsByTagName('script')[0].parentNode).insertBefore(scriptElt1,null);}
}};utag.o[loader].loader.LOAD(id);})("247","redoute.main");}catch(error){utag.DB(error);}
