//tealium universal tag - utag.246 ut4.0.202412041458, Copyright 2024 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
u.ev={"view":1,"link":1};u.initialized=false;u.map={};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
var hash=b['RTB_House_Account_ID'];var UID;if(typeof b['user_email_sha256']!=='undefined'){UID=b['user_email_sha256'];}else{UID='unknown';}
var usergroup;if(typeof b['seg_engagement']!=='undefined'||b['seg_engagement']!==''){usergroup=b['seg_engagement'];}else{usergroup='unknown';}
var page_breadcrumb;if(b.env_country==='DE'){page_breadcrumb=b['js_page.page_breadcrumb_label_str'];}else{page_breadcrumb=b['js_page.page_breadcrumb_id_str'];}
(function(w,d,dn,t){w[dn]=w[dn]||[];w[dn].push({eventType:'init',value:t,dc:''});var f=d.getElementsByTagName('script')[0],c=d.createElement('script');c.async=true;c.src='https://tags.creativecdn.com/'+hash+'.js';f.parentNode.insertBefore(c,f);})(window,document,'rtbhEvents',hash);var eventsAdded=false;if(b.pageType==='HomePage'){(rtbhEvents=window.rtbhEvents||[]).push({eventType:'home'},{eventType:'uid',id:UID});eventsAdded=true;}
if(b.pageType==='ListPage'||b.pageType==='StaticPage'){(rtbhEvents=window.rtbhEvents||[]).push({eventType:'category',categoryId:page_breadcrumb},{eventType:'uid',id:UID});eventsAdded=true;}
if(b.pageType==='MultiProductPage'||b.pageType==='ProductPage'){(rtbhEvents=window.rtbhEvents||[]).push({eventType:'offer',offerId:b.product_id},{eventType:'uid',id:UID});eventsAdded=true;}
if(b.pageType==='SearchPage'){(rtbhEvents=window.rtbhEvents||[]).push({eventType:'listing',offerIds:b._cprod},{eventType:'uid',id:UID});eventsAdded=true;}
if(b.pageType==='AddToCartLayer'){(rtbhEvents=window.rtbhEvents||[]).push({eventType:'basketadd',offerId:b.product_id},{eventType:'uid',id:UID});eventsAdded=true;}
if(String(b['cp.s_ppv']).includes('Wishlist')){(rtbhEvents=window.rtbhEvents||[]).push({eventType:'wishlist',offerId:b.product_id},{eventType:'uid',id:UID});eventsAdded=true;}
if(b.pageType==='BasketPage'){(rtbhEvents=window.rtbhEvents||[]).push({eventType:'basketstatus',offerIds:b._cprod},{eventType:'uid',id:UID});eventsAdded=true;}
if(b.pageType==='BasketPage'){(rtbhEvents=window.rtbhEvents||[]).push({eventType:'startorder',},{eventType:'uid',id:UID});eventsAdded=true;}
if(b.pageType==='ConfirmationOrderPage'){(rtbhEvents=window.rtbhEvents||[]).push({eventType:'conversion',conversionClass:'order',conversionSubClass:'purchase',conversionId:b._corder,offerIds:b._cprod,conversionValue:b._csubtotal,conversionCurrency:b._ccurrency},{eventType:'uid',id:UID});eventsAdded=true;}
if(!eventsAdded){(rtbhEvents=window.rtbhEvents||[]).push({eventType:'placebo'});}
(rtbhEvents=window.rtbhEvents||[]).push({eventType:'custom',name:'language',value:b.env_country},{eventType:'custom',name:'usergroup',value:usergroup});}};utag.o[loader].loader.LOAD(id);})("246","redoute.main");}catch(error){utag.DB(error);}
