//tealium universal tag - utag.78 ut4.0.202412041458, Copyright 2024 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
u.ev={"view":1,"link":1};u.initialized=false;u.map={};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
try{var variablesList=[];var order_product_id=[];var page_breadcrumb_id=[];var user_id_md5=b['user_id_md5']
var parameters="";variablesList.push("product_id");variablesList.push("env_template");variablesList.push("user_id");variablesList.push("order_amount_tf_without_sf");variablesList.push("multi_products_number");variablesList.push("order_id");variablesList.push("order_promo_code");variablesList.push("order_shipping_method");variablesList.push("order_payment_methods");variablesList.push("multi_products_id");variablesList.push("product_gamme");variablesList.push("product_concept_number");variablesList.push("product_ean");variablesList.push("search_keywords");variablesList.push("products_unitprice_ati");variablesList.push("virtual_site");variablesList.forEach(function(item){if(typeof(b[item])!='undefined'){if(b[item]!==''){switch(item){case"user_id":parameters+=item+"="+user_id_md5+"&";break;case"search_keywords":var elem=document.createElement('textarea');elem.innerHTML=b.search_keywords;parameters+=item+"="+escape(elem.value)+"&";break;default:parameters+=item+"="+b[item]+"&";}}}});parameters+="host="+window.location.hostname+"&";parameters+="url="+document.URL.replace(/#.*$/,"")+"&";if(b['qp.cod']!==undefined){parameters+="cod="+b['qp.cod']+"&";}
if(b['qp.omniturecode']!==undefined){parameters+="omniturecode="+b['qp.omniturecode']+"&";}
parameters+="lrdataid="+b['cp.LR_DATAID_M']+"&";parameters+="lrvisitorguid="+b['cp.LR_Visitor_Guid']+"&";if(typeof(b["multi_products_id"])!='undefined'){for(i=0;i<b["multi_products_id"].length;i++){order_product_id.push(b["multi_products_id"][i]);}
parameters+="multi_products_id="+order_product_id.join("|")+"&";}
if(typeof(b["page_breadcrumb_id"])!='undefined'){for(i=0;i<b["page_breadcrumb_id"].length;i++){page_breadcrumb_id.push(b["page_breadcrumb_id"][i]);}
parameters+="page_breadcrumb_id="+page_breadcrumb_id.join("|")+"&";}
(new Image()).src='https://streaming-data-laredoute.fr/pixel.png?'+parameters;}
catch(e){}
}};utag.o[loader].loader.LOAD(id);})("78","redoute.main");}catch(error){utag.DB(error);}
