//tealium universal tag - utag.193 ut4.0.202412041458, Copyright 2024 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
u.ev={"view":1,};u.initialized=false;u.map={};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
if(utag_data.concat_country_language.includes('LU'))
{iso_code="la-redoute-be";}else{switch(b.concat_country_language){case"FR:FR":case"DE:DE":iso_code="la-redoute";break;default:iso_code="la-redoute-"+b['iso_code'];break;}}
var domain_iso_code;switch(true){case utag_data['dom.domain'].indexOf("com")!==-1:domain_iso_code="la-redoute-com";break;}
var EBalreadyInstanciated=window._ebq;if(!EBalreadyInstanciated){var selected_iso_code=domain_iso_code||iso_code;var elt=document.createElement('script');elt.type='text/javascript';elt.async=true;elt.src='https://cdn.early-birds.fr/tenants/'+selected_iso_code+'/earlybirds-full.min.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(elt,s);}
}};utag.o[loader].loader.LOAD(id);})("193","redoute.main");}catch(error){utag.DB(error);}
